// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaa-WsO1oCdcyn2GwOnnfTEeFg_wXUTEA',
    appId: '1:971679369259:web:005533d61778893cb7c26e',
    messagingSenderId: '971679369259',
    projectId: 'taller3-2cbc0',
    authDomain: 'taller3-2cbc0.firebaseapp.com',
    storageBucket: 'taller3-2cbc0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChrrQE_eVbeQIw9JQkXSWqAHH6s003dj4',
    appId: '1:971679369259:android:a479d1a0af6c3b4bb7c26e',
    messagingSenderId: '971679369259',
    projectId: 'taller3-2cbc0',
    storageBucket: 'taller3-2cbc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1XKx3i41UwrLYOhpG23HJlfKW0VQGw0Y',
    appId: '1:971679369259:ios:927870c991a00e1db7c26e',
    messagingSenderId: '971679369259',
    projectId: 'taller3-2cbc0',
    storageBucket: 'taller3-2cbc0.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1XKx3i41UwrLYOhpG23HJlfKW0VQGw0Y',
    appId: '1:971679369259:ios:927870c991a00e1db7c26e',
    messagingSenderId: '971679369259',
    projectId: 'taller3-2cbc0',
    storageBucket: 'taller3-2cbc0.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaa-WsO1oCdcyn2GwOnnfTEeFg_wXUTEA',
    appId: '1:971679369259:web:ab32b8ee858d953cb7c26e',
    messagingSenderId: '971679369259',
    projectId: 'taller3-2cbc0',
    authDomain: 'taller3-2cbc0.firebaseapp.com',
    storageBucket: 'taller3-2cbc0.firebasestorage.app',
  );
}
